Educama/Showcase

acceptance-tests/pom.xml
acceptance-tests/src/test/resources/logback.xml
acceptance-tests/src/test/resources/serenity.properties
backend/src/main/resources/logback.xml

Logback is integrated into Spring Boot. It is only needed to add a logback.xml in the classpath ;)

Better logging integrated.

---

frontend/build.sh

removed newline to make it a "real" executable script for fish

fix build script for frontend

---

backend/pom.xml
backend/src/main/java/org/educama/shipment/api/ShipmentController.java
backend/src/main/java/org/educama/shipment/api/resource/ShipmentListResource.java
backend/src/main/java/org/educama/shipment/api/resource/ShipmentResource.java
backend/src/main/java/org/educama/shipment/boundary/ShipmentBoundaryService.java
backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentBoundaryServiceImpl.java
backend/src/main/java/org/educama/shipment/control/ShipmentCaseControlService.java
backend/src/main/java/org/educama/shipment/model/Shipment.java
backend/src/main/java/org/educama/shipment/repository/ShipmentRepository.java
backend/src/main/resources/cmmn/shipment.cmmn

The backend will offer a ReST API which was developed in a technically working approach. A repository and the usage of a CMMN-engine are going to be developed.

ECM-46: Create Backend Example

---

backend/src/main/java/org/educama/configuration/DefaultUserConfiguration.java

Added logging to DefaultUserConfiguration

ECM-61: Added logging to DefaultUserConfiguration

---

backend/src/main/java/org/educama/shipment/api/resource/ShipmentResource.java
backend/src/main/java/org/educama/shipment/model/Shipment.java

Added customerId to ShipmentResource.java and Shipment.java

ECM-44: Added customer to ShipmentResource.java and Shipment.java

---

backend/src/main/java/org/educama/application/lifecycle/DefaultUserLifecycleBean.java
backend/src/main/java/org/educama/application/lifecycle/DemoCustomerLifecycleBean.java

This PR relies on the other PR to be integrated first. As you can see, the commits of the other PR are also integrated here. As soon as the other PR is integrated, the "diff" compared to the master will just contain the commit for ECM-92.

ECM-92 Create Demo Customers on Application Start

---

backend/pom.xml
backend/src/main/java/org/educama/common/api/resource/PageLinksAspect.java
backend/src/main/java/org/educama/common/exceptions/PreconditionViolationException.java
backend/src/main/java/org/educama/common/exceptions/ResourceNotFoundException.java
backend/src/main/java/org/educama/configuration/CorsConfiguration.java
backend/src/main/java/org/educama/configuration/CorsProperties.java
backend/src/main/java/org/educama/customer/model/Customer.java

Removed all warnings and made build fail, if new warnings occur.
Some bigger changes in CorsProperties and CorsConfiguration.

Ecm 32: Enforce zero warning policy

---

backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentBoundaryServiceImpl.java

Updated the put method since it threw an error due to the last flyway change

ECM-170 : Update Put Method

---

services/educama-supplier-simulator-backend/server.js

Create new rest api so that Angular front end could obtain booking events as the same way as backend service

ECM-188: New REST API for booking Events

---

frontend/src/app/shipment/shipment-common/effects/task-list.effect.ts

The described bug in ECM-211 is fixed. The effect referenced on shipment-list in some parts.

ECM-211: changed wrong references from shipmentlist to tasklist.

---

manifests/pcfdev.yml
scripts/pcfdev/deploy.sh
scripts/pcfdev/login.sh
scripts/pcfdev/services.sh
scripts/pcfdev/start.sh
scripts/pcfdev/stop.sh
services/educama-supplier-simulator-backend/README.md
services/educama-supplier-simulator-backend/educama-supplier-simulator-database-service.json
services/flightinformation/README.txt
services/flightinformation/UserProvidedService.json
services/flightinformation/educama-flight-information-database-service.json

This pull request contains a few convenient scripts to deploy the educama stack on pcf-dev.

Add scripts for easy deployment of educama on pcf-dev.

---

api/src/main/resources/application.yml
backend/pom.xml
backend/src/main/resources/application-local.properties
scripts/common/helpers.sh
scripts/docker/docker-compose.yml
scripts/docker/down.sh
scripts/docker/start.sh
scripts/docker/stop.sh
scripts/docker/up.sh
services/flightinformation/README.txt
services/flightinformation/src/main/resources/application-local.properties
services/flightinformation/src/main/resources/application.properties

With this pull request, a docker-compose script as well as some helper scripts are added to start all required docker containers locally for development. 
In addition, a spring profile "local" was added that can be used when starting the backend locally. This profile configures the local MySQL database (started in the docker container) to be used.

ECM-256: Add docker-compose script and local profile for backend service

---

backend/src/main/java/org/educama/shipment/model/Flight.java
backend/src/main/java/org/educama/shipment/model/InstantConverter.java
backend/src/main/resources/db/migration/common/V01_010__change_date_datatypes.sql

hopefully this resolves existing errors on live enviroment

ECM-272: Fixing errors in Live-System concerning dateformat types

---

backend/Educama-Backend.postman_collection.json
backend/src/main/asciidoc/rest-api.adoc
backend/src/test/java/org/educama/common/api/RestApiDocumentation.java

Updated the documentation including Postman and REST API documentation for all existing SHIPMENT and TASK services. Customer services are still ok.

ECM-288: Update Documentation for all services

---

backend/src/main/java/org/educama/shipment/api/resource/SaveShipmentResource.java
backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentBoundaryServiceImpl.java
backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentTaskBoundaryServiceImpl.java
frontend/src/app/shipment/shipment-capture/container/shipment-capture-page.component.ts

Noch eine weitere Stelle gefunden an der keine null Werte akzeptiert werden.
Zusätzlich einen Workaround ausgebaut der diesen Umstand im Frontend kaschiert.

ECM-272: Fixed errors in SaveShipmentResource and transaction handling

---

backend/Educama-Backend.postman_collection.json
backend/src/main/asciidoc/rest-api.adoc
backend/src/main/java/org/educama/shipment/api/ShipmentController.java
backend/src/main/java/org/educama/shipment/api/resource/InvoiceResource.java
backend/src/main/java/org/educama/shipment/api/resource/SaveInvoiceResource.java
backend/src/main/java/org/educama/shipment/boundary/ShipmentBoundaryService.java
backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentBoundaryServiceImpl.java
backend/src/main/java/org/educama/shipment/model/Invoice.java
backend/src/main/java/org/educama/shipment/process/tasks/CreateInvoiceTask.java
backend/src/main/java/org/educama/shipment/repository/InvoiceRepository.java
backend/src/main/resources/db/migration/common/V01_010__create_invoice.sql
backend/src/test/java/org/educama/common/api/RestApiDocumentation.java

Notwendige Backend Anpassungen um create invoice zu ermöglichen.

ECM-230: Backend changes for create invoice

---

backend/Educama-Backend.postman_collection.json
backend/src/main/java/org/educama/shipment/api/ShipmentController.java
backend/src/main/java/org/educama/shipment/api/resource/InvoiceListResource.java
backend/src/main/java/org/educama/shipment/boundary/ShipmentBoundaryService.java
backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentBoundaryServiceImpl.java
backend/src/main/java/org/educama/shipment/repository/InvoiceRepository.java
backend/src/test/java/org/educama/common/api/RestApiDocumentation.java

Created REST-Service to get all invoices of one shipment.
Also updated REST-Tests acordingly

ECM-281: Create REST-Service to get invoice(s) for a shipment

---

frontend/src/app/shipment/shipment-invoice/presentationals/shipment-invoice.component.html

Corrected a wrong translation.

ECM-290: Correct wrong translations in Invoice component

---

backend/Educama-Backend.postman_collection.json
backend/src/main/java/org/educama/common/persistence/InstantConverter.java
backend/src/main/java/org/educama/shipment/model/Flight.java
backend/src/main/java/org/educama/shipment/model/Invoice.java
backend/src/main/java/org/educama/shipment/model/Shipment.java

- ECM-295: Fixes error happend while compliting a shipment
- Refactoring: Moved InstantCoverter to package common/persistence
- Postman Collection: Fixed errors in create/update shipment REST-calls.

ECM-295 & Refactoring

---

backend/Educama-Backend.postman_collection.json
backend/src/main/java/org/educama/common/api/BeanUtil.java
backend/src/main/java/org/educama/enums/Status.java
backend/src/main/java/org/educama/shipment/api/ShipmentController.java
backend/src/main/java/org/educama/shipment/api/resource/SaveShipmentResource.java
backend/src/main/java/org/educama/shipment/api/resource/ShipmentResource.java
backend/src/main/java/org/educama/shipment/boundary/ShipmentBoundaryService.java
backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentBoundaryServiceImpl.java
backend/src/main/java/org/educama/shipment/boundary/impl/ShipmentTaskBoundaryServiceImpl.java
backend/src/main/java/org/educama/shipment/control/caseExecutionListener/FlightDepartedListener.java
backend/src/main/java/org/educama/shipment/control/caseExecutionListener/ShipmentCompletedListener.java
backend/src/main/java/org/educama/shipment/model/Shipment.java
backend/src/main/java/org/educama/shipment/process/ShipmentCaseConstants.java
backend/src/main/java/org/educama/shipment/process/milestones/FlightDeparted.java
backend/src/main/java/org/educama/shipment/process/sentries/FlightDepartedSentry.java
backend/src/main/resources/cmmn/ShipmentCase.cmmn
backend/src/main/resources/db/migration/common/V01_011__add_status_to_shipment.sql
backend/src/test/java/org/educama/common/api/RestApiDocumentation.java
backend/src/test/java/org/educama/customer/api/CustomerControllerIntTest.java
backend/src/test/java/org/educama/shipment/process/ShipmentCaseModelTest.java

All backend changes for the new milestone flight departed

ECM-292: Process flight departed milestone
